// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
theme_style_select : '-- סיגנ&aring;נ&aring;ת --',
theme_code_desc : 'ער&aring;ך את ק&aring;ד &auml;-HTML',
theme_code_title : 'ע&aring;רך ק&aring;ד HTML',
theme_code_wordwrap : 'גלישת ש&aring;ר&aring;ת',
theme_sub_desc : 'כתב תחתי',
theme_sup_desc : 'כתב עילי',
theme_hr_desc : '&auml;כנס ק&aring; א&aring;פקי',
theme_removeformat_desc : '&auml;סר עי&ouml;&aring;ב',
theme_custom1_desc : '&auml;תיא&aring;ר שלך כאן',
insert_image_border : 'גב&aring;ל',
insert_image_dimensions : 'מימדים',
insert_image_vspace : 'חלל אנכי',
insert_image_hspace : 'חלל א&aring;פקי',
insert_image_align : 'ייש&aring;ר',
insert_image_align_default : 'ברירת מחדל',
insert_image_align_baseline : 'לק&aring; &auml;בסיס',
insert_image_align_top : 'למעל&auml;',
insert_image_align_middle : 'לאמ&ouml;ע',
insert_image_align_bottom : 'למט&auml;',
insert_image_align_texttop : 'לראש &auml;טקסט',
insert_image_align_absmiddle : 'לאמ&ouml;ע מ&aring;חלט',
insert_image_align_absbottom : 'לק&ouml;&auml; תחת&aring;ן מ&aring;חלט',
insert_image_align_left : 'לשמאל',
insert_image_align_right : 'לימין',
theme_font_size : 'ג&aring;דל ג&aring;פן',
theme_fontdefault : '-- משפחת ג&aring;פנים --',
theme_block : '-- עי&ouml;&aring;ב --',
theme_paragraph : 'פסק&auml;',
theme_div : 'קטע',
theme_address : 'כת&aring;בת',
theme_pre : 'מע&aring;&ouml;ב מראש',
theme_h1 : 'כ&aring;תרת 1',
theme_h2 : 'כ&aring;תרת 2',
theme_h3 : 'כ&aring;תרת 3',
theme_h4 : 'כ&aring;תרת 4',
theme_h5 : 'כ&aring;תרת 5',
theme_h6 : 'כ&aring;תרת 6',
theme_colorpicker_title : 'בחר &ouml;בע',
theme_colorpicker_apply : '&auml;חל',
theme_forecolor_desc : 'בחר &ouml;בע טקסט',
theme_backcolor_desc : 'בחר &ouml;בע רקע',
theme_charmap_title : 'בחר ת&aring; מי&aring;חד',
theme_charmap_desc : '&auml;כנס ת&aring; מי&aring;חד',
theme_visualaid_desc : '&auml;חלף מ&ouml;ב ק&aring;&aring;ים מנחים/רכיבים בלתי-נראים',
insert_anchor_title : '&auml;כנס/ער&aring;ך ע&aring;גן',
insert_anchor_name : 'שם &auml;ע&aring;גן',
theme_anchor_desc : '&auml;כנס/ער&aring;ך ע&aring;גן',
theme_insert_link_titlefield : 'כ&aring;תרת',
theme_clipboard_msg : 'פע&aring;ל&aring;ת &auml;עתק&auml;/גזיר&auml;/&auml;דבק&auml; אינן נתמכ&aring;ת תחת Mozilla &aring;-Firefox.\n&auml;אם בר&ouml;&aring;נך לקבל מידע נ&aring;סף א&aring;ד&aring;ת נ&aring;שא ז&auml;?',
theme_path : 'נתיב',
cut_desc : 'גז&aring;ר',
copy_desc : '&auml;עתק',
paste_desc : '&auml;דבק',
link_list : 'רשימת קיש&aring;רים',
image_list : 'רשימת תמ&aring;נ&aring;ת',
browse : 'סייר',
image_props_desc : 'מאפייני תמ&aring;נ&auml;',
newdocument_desc : 'מסמך חדש',
class_name : 'מחלק&auml;',
newdocument : '&auml;אם את&auml; בט&aring;ח שבר&ouml;&aring;נך לנק&aring;ת את כל &auml;ת&aring;כן?'
});
