<?php
/*
	Helios Calendar - Professional Event Management System
	Copyright © 2006 Refresh Web Development [http://www.refreshwebdev.com]
	
	Developed By: Chris Carlevato <chris@refreshwebdev.com>
	
	For the most recent version, visit the Helios Calendar website:
	[http://www.helioscalendar.com]
	
	License Information is found in docs/license.html
*/
	if(isset($_GET['print'])){
	include('../../events/includes/headerAdmin.php');	?>
		<title><?echo CalName;?> Overview Report</title>
	</head>

	<body<?if(!isset($_SESSION['AdminLoggedIn'])){echo " onload=\"document.frm.elements[0].focus();\"";}//end if?>>
<?	if(!isset($_SESSION['AdminLoggedIn'])){
		exit;
	}//end if	?>
	<div style="width:550px;">
	<div style="float:left;width:350px;">
		<span style="font-family:verdana;font-size:15px;font-weight:bold;"><?echo CalName;?> Overview Report</span><br />
		<b>Created at:</b> <?echo date("Y-m-d g:i:s A");?><br />
		<b>Calendar:</b> <?echo CalRoot;?>/<br />
		<b>Generated by:</b> Helios Calendar <?echo HC_Version;?>
	</div>
	<div style="float:left;width:200px;text-align:right;vertical-align:top;">
		<img src="<?echo CalAdminRoot;?>/images/logo.gif" width="200" height="50" alt="" border="0" />
		<br />www.HeliosCalendar.com
	</div>
	<br /><br />
<?	} else {	?>
		<div align="right"><img src="<?echo CalAdminRoot;?>/images/icons/iconPrint.gif" width="15" height="15" alt="" border="0" align="middle" /> <a href="<?echo CalAdminRoot;?>/components/ReportOverview.php?print=1" class="main" target="_blank">Printer Friendly</a></div>
<?	}//end if	?>
		<div class="overviewDetails"><b>Calendar Detail</b></div><div class="overviewCount"><b>Stats</b></div>
		<div class="overviewDetails">Total Events:</div>
		<div class="overviewCount">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events");
			if(hasRows($result)){
				$totalEvents = mysql_result($result,0,0);
				echo $totalEvents;
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetailsHL">Active Events</div>
		<div class="overviewCountHL">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events WHERE IsActive = 1 AND IsApproved = 1 AND StartDate >= NOW()");
			if(hasRows($result)){
				$activeEvents = mysql_result($result,0,0);
				echo $activeEvents;
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetails">Passed Events</div>
		<div class="overviewCount">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events WHERE IsActive = 1 AND IsApproved = 1 AND StartDate < NOW()");
			if(hasRows($result)){
				$pastEvents = mysql_result($result,0,0);
				echo $pastEvents;
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetailsHL">Deleted Events</div>
		<div class="overviewCountHL">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events WHERE IsActive = 0");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetails">Active Billboard Events</div>
		<div class="overviewCount">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events WHERE IsActive = 1 AND IsApproved = 1 AND IsBillboard = 1 AND StartDate >= NOW()");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetailsHL">Orphan Events</div>
		<div class="overviewCountHL">
		<?	$result = doQuery("	SELECT " . HC_TblPrefix . "events.*
								FROM " . HC_TblPrefix . "events
									LEFT JOIN " . HC_TblPrefix . "eventcategories ON (" . HC_TblPrefix . "events.PkID = " . HC_TblPrefix . "eventcategories.EventID)
									LEFT JOIN " . HC_TblPrefix . "categories ON (" . HC_TblPrefix . "categories.PkID = " . HC_TblPrefix . "eventcategories.CategoryID)
								WHERE 
									" . HC_TblPrefix . "events.IsActive = 1 AND
									" . HC_TblPrefix . "events.IsApproved = 1 AND
									" . HC_TblPrefix . "events.StartDate >= NOW() AND
									(" . HC_TblPrefix . "eventcategories.EventID IS NULL OR
									" . HC_TblPrefix . "categories.IsActive = 0)
								ORDER BY StartDate");
			echo mysql_num_rows($result);?>
		</div>
		<div class="overviewDetails">Events Today</div>
		<div class="overviewCount">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events WHERE IsActive = 1 AND IsApproved = 1 AND StartDate = NOW()");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetailsHL">Events Through Next Sunday</div>
		<div class="overviewCountHL">
		<?	$now = date("Y-m-d");
			
			$addDays = 0;
			if(date("w") != 6){
				$addDays = 6 - date("w");
			}//end if
			$then = date("Y-m-d", mktime(0,0,0,date("m"),date("d") + $addDays,date("Y")));
			
			$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events WHERE IsActive = 1 AND IsApproved = 1 AND StartDate BETWEEN '" . $now . "' AND '" . $then . "'");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetails">Events Through End of Month</div>
		<div class="overviewCount">
		<?	$now = date("Y-m-d");
			$then = date("Y-m-d", mktime(0,0,0,date("m") + 1,0,date("Y")));
			
			$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "events WHERE IsActive = 1 AND IsApproved = 1 AND StartDate BETWEEN '" . $now . "' AND '" . $then . "'");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetailsHL">Active Users</div>
		<div class="overviewCountHL">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "users WHERE IsRegistered = 1");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetails">Total Users</div>
		<div class="overviewCount">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "users");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetailsHL">Earliest Event</div>
		<div class="overviewCountHL">
		<?	$result = doQuery("SELECT MIN(StartDate) FROM " . HC_TblPrefix . "events WHERE IsActive = 1");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetails">Latest Event</div>
		<div class="overviewCount">
		<?	$result = doQuery("SELECT MAX(StartDate) FROM " . HC_TblPrefix . "events WHERE IsActive = 1");
			if(hasRows($result)){
				echo mysql_result($result,0,0);
			} else {
				echo "N/A";
			}//end if?>
		</div>
		<div class="overviewDetailsHL">Average Active Events Per Category</div>
		<div class="overviewCountHL">
		<?	$result = doQuery("SELECT COUNT(*) FROM " . HC_TblPrefix . "categories WHERE IsActive = 1");
			if(hasRows($result)){
				$activeCategories = mysql_result($result,0,0);
				echo number_format($activeEvents / $activeCategories, 2, '.', ',');
			} else {
				echo "N/A";
			}//end if?>
		</div>
	<?	$result = doQuery("	SELECT SUM(Views) as Views,
									SUM(Directions) as Directions,
									SUM(Downloads) as Downloads,
									SUM(EmailToFriend) as EmailToFriend,
									SUM(URLClicks) as URLClicks,
									SUM(MViews) as MViews
								FROM " . HC_TblPrefix . "events
								WHERE IsActive = 1 AND StartDate >= NOW()");
		$aViews = mysql_result($result,0,0);
		$aDirections = mysql_result($result,0,1);
		$aDownloads = mysql_result($result,0,2);
		$aEmail = mysql_result($result,0,3);
		$aURL = mysql_result($result,0,4);
		$aMViews = mysql_result($result,0,5);	?>
		<div class="overviewDetails" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>&nbsp;<br />Active Event Stats</b></div>
		<div class="overviewAverage" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Event<br />Average</b></div>
		<div class="overviewTotal" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>&nbsp;<br />Total</b></div>
		<div class="overviewDetails">Views</div>
		<div class="overviewAverage"><?if($activeEvents > 0){echo number_format($aViews / $activeEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotal"><?if($aViews != ''){echo $aViews;}else{echo "0";}?></div>
		<div class="overviewDetailsHL">Mobile Views</div>
		<div class="overviewAverageHL"><?if($activeEvents > 0){echo number_format($aMViews / $activeEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotalHL"><?if($aMViews != ''){echo $aMViews;}else{echo "0";}?></div>
		<div class="overviewDetails">Driving Directions</div>
		<div class="overviewAverage"><?if($activeEvents > 0){echo number_format($aDirections / $activeEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotal"><?if($aDirections != ''){echo $aDirections;}else{echo "0";}?></div>
		<div class="overviewDetailsHL">Downloads</div>
		<div class="overviewAverageHL"><?if($activeEvents > 0){echo number_format($aDownloads / $activeEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotalHL"><?if($aDownloads != ''){echo $aDownloads;}else{echo "0";}?></div>
		<div class="overviewDetails">Email to Friend</div>
		<div class="overviewAverage"><?if($activeEvents > 0){echo number_format($aEmail / $activeEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotal"><?if($aEmail != ''){echo $aEmail;}else{echo "0";}?></div>
		<div class="overviewDetailsHL">URL Clicks</div>
		<div class="overviewAverageHL"><?if($activeEvents > 0){echo number_format($aURL / $activeEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotalHL"><?if($aURL != ''){echo $aURL;}else{echo "0";}?></div>
	<?	$result = doQuery("	SELECT SUM(Views) as Views,
								SUM(Directions) as Directions,
								SUM(Downloads) as Downloads,
								SUM(EmailToFriend) as EmailToFriend,
								SUM(URLClicks) as URLClicks,
								SUM(MViews) as MViews
							FROM " . HC_TblPrefix . "events
							WHERE IsActive = 1 AND StartDate < NOW()");
		$pViews = mysql_result($result,0,0);
		$pDirections = mysql_result($result,0,1);
		$pDownloads = mysql_result($result,0,2);
		$pEmail = mysql_result($result,0,3);
		$pURL = mysql_result($result,0,4);
		$pMViews = mysql_result($result,0,5);	?>
		<div class="overviewDetails" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>&nbsp;<br />Past Event Stats</b></div>
		<div class="overviewAverage" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Event<br />Average</b></div>
		<div class="overviewTotal" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>&nbsp;<br />Total</b></div>
		<div class="overviewDetails">Views</div>
		<div class="overviewAverage"><?if($pastEvents > 0){echo number_format($pViews / $pastEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotal"><?if($pViews != ''){echo $pViews;}else{echo "0";}?></div>
		<div class="overviewDetailsHL">Mobile Views</div>
		<div class="overviewAverageHL"><?if($pastEvents > 0){echo number_format($pMViews / $pastEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotalHL"><?if($pMViews != ''){echo $pMViews;}else{echo "0";}?></div>
		<div class="overviewDetails">Driving Directions</div>
		<div class="overviewAverage"><?if($pastEvents > 0){echo number_format($pDirections / $pastEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotal"><?if($pDirections != ''){echo $pDirections;}else{echo "0";}?></div>
		<div class="overviewDetailsHL">Downloads</div>
		<div class="overviewAverageHL"><?if($pastEvents > 0){echo number_format($pDownloads / $pastEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotalHL"><?if($pDownloads != ''){echo $pDownloads;}else{echo "0";}?></div>
		<div class="overviewDetails">Email to Friend</div>
		<div class="overviewAverage"><?if($pastEvents > 0){echo number_format($pEmail / $pastEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotal"><?if($pEmail != ''){echo $pEmail;}else{echo "0";}?></div>
		<div class="overviewDetailsHL">URL Clicks</div>
		<div class="overviewAverageHL"><?if($pastEvents > 0){echo number_format($pURL / $pastEvents, 2, '.', ',');}else{echo "0";}?></div>
		<div class="overviewTotalHL"><?if($pURL != ''){echo $pURL;}else{echo "0";}?></div>
	<?	$result = doQuery("	SELECT SUM(Views) as Views,
								SUM(Directions) as Directions,
								SUM(Downloads) as Downloads,
								SUM(EmailToFriend) as EmailToFriend,
								SUM(URLClicks) as URLClicks,
								SUM(MViews) as MViews
							FROM " . HC_TblPrefix . "events");
		$tViews = mysql_result($result,0,0);
		$tDirections = mysql_result($result,0,1);
		$tDownloads = mysql_result($result,0,2);
		$tEmail = mysql_result($result,0,3);
		$tURL = mysql_result($result,0,4);
		$tMViews = mysql_result($result,0,5);	?>
		<div class="overviewDetails" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>&nbsp;<br />Total Event Stats</b></div>
		<div class="overviewAverage" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Event<br />Average</b></div>
		<div class="overviewTotal" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>&nbsp;<br />Total</b></div>
		<div class="overviewDetails">Views</div>
		<div class="overviewAverage"><?echo number_format($tViews / $totalEvents, 2, '.', ',');?></div>
		<div class="overviewTotal"><?echo $tViews;?></div>
		<div class="overviewDetailsHL">Mobile Views</div>
		<div class="overviewAverageHL"><?echo number_format($tMViews / $totalEvents, 2, '.', ',');?></div>
		<div class="overviewTotalHL"><?echo $tMViews;?></div>
		<div class="overviewDetails">Driving Directions</div>
		<div class="overviewAverage"><?echo number_format($tDirections / $totalEvents, 2, '.', ',');?></div>
		<div class="overviewTotal"><?echo $tDirections;?></div>
		<div class="overviewDetailsHL">Downloads</div>
		<div class="overviewAverageHL"><?echo number_format($tDownloads / $totalEvents, 2, '.', ',');?></div>
		<div class="overviewTotalHL"><?echo $tDownloads;?></div>
		<div class="overviewDetails">Email to Friend</div>
		<div class="overviewAverage"><?echo number_format($tEmail / $totalEvents, 2, '.', ',');?></div>
		<div class="overviewTotal"><?echo $tEmail;?></div>
		<div class="overviewDetailsHL">URL Clicks</div>
		<div class="overviewAverageHL"><?echo number_format($tURL / $totalEvents, 2, '.', ',');?></div>
		<div class="overviewTotalHL"><?echo $tURL;?></div>

	<?	if(isset($_GET['print'])){	?>
			<div style="clear:both;width:650px;padding: 10px 0px 0px 0px;">
				<span class="main"><b>Generated by Helios Calendar <?echo HC_Version;?> -- www.HeliosCalendar.com</b></span>
				<p style="page-break-before: always;"><span class="main"><b><?echo CalName;?> Calendar Overview -- Page 2/4</b></span></p>
			</div>
	<?	} else {	?>
			<br /><br />
	<?	}//end if	
		
		$result = doQuery("SELECT Title, StartDate, Views FROM " . HC_TblPrefix . "events WHERE IsApproved = 1 AND Views > 0 ORDER BY Views DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS" style="padding-top:10px;"><b>Most Viewed Events</b></div>
			<div class="overviewDate" style="padding-top:10px;"><b>Date</b></div>
			<div class="overviewTotal" style="padding-top:10px;"><b>Count</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[1];?></div>
				<div class="overviewTotal<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[2];?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Most Viewed Events</b> report.</div>
	<?	}//end if
			
		$result = doQuery("SELECT Title, StartDate, MViews FROM " . HC_TblPrefix . "events WHERE IsApproved = 1 AND MViews > 0 ORDER BY MViews DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS" style="padding-top:10px;"><b>Most Mobile Viewed Events</b></div>
			<div class="overviewDate" style="padding-top:10px;"><b>Date</b></div>
			<div class="overviewTotal" style="padding-top:10px;"><b>Count</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[1];?></div>
				<div class="overviewTotal<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[2];?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Most Mobile Viewed Events</b> report.</div>
	<?	}//end if
		
		$result = doQuery("SELECT Title, StartDate, Directions FROM " . HC_TblPrefix . "events WHERE IsApproved = 1 AND Directions > 0 ORDER BY Directions DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS" style="padding-top:10px;"><b>Most Driving Directions</b></div>
			<div class="overviewDate" style="padding-top:10px;"><b>Date</b></div>
			<div class="overviewTotal" style="padding-top:10px;"><b>Count</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[1];?></div>
				<div class="overviewTotal<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[2];?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Most Driving Directions</b> report.</div>
	<?	}//end if
		
		if(isset($_GET['print'])){	?>
			<div style="clear:both;width:650px;padding: 10px 0px 0px 0px;">
				<span class="main"><b>Generated by Helios Calendar <?echo HC_Version;?> -- www.HeliosCalendar.com</b></span>
				<p style="page-break-before: always;"><span class="main"><b><?echo CalName;?> Calendar Overview -- Page 3/4</b></span></p>
			</div>
	<?	}//end if	
		
		$result = doQuery("SELECT Title, StartDate, Downloads FROM " . HC_TblPrefix . "events WHERE IsApproved = 1 AND Downloads > 0 ORDER BY Downloads DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS" style="padding-top:10px;"><b>Most Downloads</b></div>
			<div class="overviewDate" style="padding-top:10px;"><b>Date</b></div>
			<div class="overviewTotal" style="padding-top:10px;"><b>Count</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[1];?></div>
				<div class="overviewTotal<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[2];?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Most Downloads</b> report.</div>
	<?	}//end if
		
		$result = doQuery("SELECT Title, StartDate, EmailToFriend FROM " . HC_TblPrefix . "events WHERE IsApproved = 1 AND EmailToFriend > 0 ORDER BY EmailToFriend DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS" style="padding-top:10px;"><b>Most Email to Friend</b></div>
			<div class="overviewDate" style="padding-top:10px;"><b>Date</b></div>
			<div class="overviewTotal" style="padding-top:10px;"><b>Count</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[1];?></div>
				<div class="overviewTotal<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[2];?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Most Email to Friend</b> report.</div>
	<?	}//end if
		
		$result = doQuery("SELECT Title, StartDate, URLClicks FROM " . HC_TblPrefix . "events WHERE IsApproved = 1 AND URLClicks > 0 ORDER BY URLClicks DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS" style="padding-top:10px;"><b>Most URL Clicks</b></div>
			<div class="overviewDate" style="padding-top:10px;"><b>Date</b></div>
			<div class="overviewTotal" style="padding-top:10px;"><b>Count</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[1];?></div>
				<div class="overviewTotal<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[2];?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Most URL Clicks</b> report.</div>
	<?	}//end if
		
		if(isset($_GET['print'])){	?>
			<div style="clear:both;width:650px;padding: 10px 0px 0px 0px;">
				<span class="main"><b>Generated by Helios Calendar <?echo HC_Version;?> -- www.HeliosCalendar.com</b></span>
				<p style="page-break-before: always;"><span class="main"><b><?echo CalName;?> Calendar Overview -- Page 4/4</b></span></p>
			</div>
	<?	} else {	?>
			<br /><br />
	<?	}//end if	
		
		$result = doQuery("SELECT Title, StartDate, PublishDate FROM " . HC_TblPrefix . "events WHERE StartDate >= NOW() AND IsApproved = 1 AND IsActive = 1 ORDER BY PublishDate DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS2" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Recently Added Events</b></div>
			<div class="overviewDate" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Event Date</b></div>
			<div class="overviewDate" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Published</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS2<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo stampToDate($row[1], "Y-m-d");?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo stampToDate($row[2], "Y-m-d");?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Recently Added Events</b> report.</div>
	<?	}//end if
		
		$result = doQuery("SELECT Title, StartDate, PublishDate FROM " . HC_TblPrefix . "events WHERE IsApproved = 1 AND SubmittedByName IS NOT NULL ORDER BY PublishDate DESC, Title LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewDetailS2" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Recently Submitted Events</b></div>
			<div class="overviewDate" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Event Date</b></div>
			<div class="overviewDate" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Published</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewDetailS2<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo stampToDate($row[1], "Y-m-d");?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo stampToDate($row[2], "Y-m-d");?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Recently Submitted Events</b> report.</div>
	<?	}//end if
		
		$result = doQuery("SELECT FirstName, LastName, Email, RegisteredAt FROM " . HC_TblPrefix . "users WHERE IsRegistered = 1 ORDER BY RegisteredAt DESC, LastName, FirstName LIMIT 10");
		if(hasRows($result)){	?>
			<div class="overviewName" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Newest Users</b></div>
			<div class="overviewEmail" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Email</b></div>
			<div class="overviewDate" style="padding-top:10px;line-height:11px;vertical-align:bottom;"><b>Registered</b></div>
	<?		$cnt = 0;
			while($row = mysql_fetch_row($result)){	?>
				<div class="overviewName<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[0] . " " . $row[1];?></div>
				<div class="overviewEmail<?if($cnt % 2 == 1){echo "HL";}?>"><?echo $row[2];?></div>
				<div class="overviewDate<?if($cnt % 2 == 1){echo "HL";}?>"><?echo stampToDate($row[3], "Y-m-d");?></div>
	<?		$cnt++;
			}//end while
		} else {	?>
			<div style="clear:both;padding: 20px 0px 0px 0px;">There are no events currently available for the <b>Newest Users</b> report.</div>
	<?	}//end if
		
		if(isset($_GET['print'])){	?>
			<div style="clear:both;width:650px;padding: 10px 0px 0px 0px;">
				<span class="main"><b>Generated by Helios Calendar <?echo HC_Version;?> -- www.HeliosCalendar.com</b></span>
			</div>
	<?	}//end if	
	
	if(isset($_GET['print'])){	?>
		</div>
		</body>
		</html>
<?	}//end if	?>
	