<?php
/*
	Helios Calendar
	Copyright (C) 2004-2010 Refresh Web Development, LLC. [www.RefreshMy.com]

	This file is part of Helios Calendar, it's usage is governed by
	the Helios Calendar SLA found at www.HeliosCalendar.com/license.html
*/
	$isAction = 1;
	include('../includes/include.php');
	include('../' . $hc_langPath . $_SESSION[$hc_cfg00 . 'LangSet'] . '/config.php');
	include('../' . $hc_langPath . $_SESSION[$hc_cfg00 . 'LangSet'] . '/public/rss.php');
	
	$hourOffset = date("G") + ($hc_cfg35);
	$tzOffset = date("O") + ($hc_cfg35 * 100);
	$cID = (isset($_GET['cID']) && is_numeric($_GET['cID'])) ? cIn($_GET['cID']) : -1;
	
	if($tzOffset == 0){
		$tzOffset = "+0000";
	} elseif($tzOffset < 0){
		if(strlen($tzOffset) < 5){
			$tzOffset = ltrim($tzOffset,"-");
			$tzOffset = "-0" . $tzOffset;
		}//end if
	} elseif($tzOffset > 0) {
		$tzOffset = (strlen($tzOffset) < 4) ? '+0' . $tzOffset : '+' . $tzOffset;
	}//end if
	
	$result = doQuery("SELECT e.PkID, e.Title, c.Comment, c.PostTime, oid.ShortName, c.PkID
					FROM " . HC_TblPrefix . "comments c
						LEFT JOIN " . HC_TblPrefix . "events e ON (c.EntityID = e.PkID)
						LEFT JOIN " . HC_TblPrefix . "oidusers oid ON (oid.PkID = c.PosterID)
					WHERE e.PkID = '" . cIn($cID) . "' AND
						e.IsActive = 1 AND
						c.IsActive = 1 AND
						c.Recomnds > " . $hc_cfg53 . "
					ORDER BY PostTime");

	header('Content-Type:application/rss+xml; charset=' . $hc_lang_config['CharSet']);
	echo "<?xml version=\"1.0\" encoding=\"" . $hc_lang_config['CharSet'] . "\"?>";
	echo "\n<?xml-stylesheet type=\"text/css\" href=\"" . CalRoot . "/css/rss.css\"?>";
	
	echo "\n" . '<!-- Generated by Helios Calendar ' . $hc_cfg49 . ' ' . date("\\o\\n Y-m-d \\a\\t H:i:s") . ' local time. -->';
	echo "\n" . '<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">';
	echo "\n" . '<channel>';
	echo "\n" . '<link>' . CalRoot . '/</link>';
	echo "\n" . '<copyright>Copyright 2004-' . date("Y") . ' Refresh Web Development, LLC.</copyright>';
	echo "\n" . '<generator>http://www.HeliosCalendar.com</generator>';
	echo "\n" . '<docs>' . CalRoot . '&#47;index.php&#63;com=rss</docs>';
	echo "\n" . '<description>Event Comment Information From ' . CalName . '</description>';
	
	if(hasRows($result)){
		echo "\n" . '<title>' . mysql_result($result,0,1) . ' - ' . $hc_lang_rss['Comments'] . '</title>';
		$cnt = 0;
		mysql_data_seek($result,0);
		while($row = mysql_fetch_row($result)){
			if($cnt >= $hc_cfg2){break;}

			echo "\n" . '<item>';
			echo "\n" . '<title>' . $row[4] . ' ' . $hc_lang_rss['Said'];
			echo "\n" . '</title>';
			echo "\n" . '<link><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . '#cmnts]]></link>';
			echo "\n" . '<description>' . html_entity_decode(cleanXMLChars(cOut($row[2]))) . '</description>';
			echo "\n" . '<guid>' . CalRoot . '/index.php&#63;com=detail&amp;eID=' . $row[0] . '#cmnts_' . $row[5] . '</guid>';

			$stampParts = explode(" ", $row[3]);
			$dateParts = explode("-",$stampParts[0]);
			$timeParts = explode(":",$stampParts[1]);
			$hour = (isset($timeParts[1])) ? $timeParts[0] : 0;
			$min = (isset($timeParts[1])) ? $timeParts[1] : 0;
			$sec = (isset($timeParts[1])) ? $timeParts[2] : 0;
			echo "\n" . '<pubDate>' . cleanXMLChars(date("D\, d M Y H:i:s", mktime($hour,$min,$sec,$dateParts[1],$dateParts[2],$dateParts[0])) . ' ' . $tzOffset) . '</pubDate>';
			echo "\n" . '</item>';
			++$cnt;
		}//end while
	} else {
		echo "\n" . '<item>';
		echo "\n" . '<title>' . $hc_lang_rss['RSSNoEvents'] . '</title>';
		echo "\n" . '<link>' . CalRoot . '/</link>';
		echo "\n" . '<description>' . $hc_lang_rss['RSSMoreInfo'] . '</description>';
		echo "\n" . '</item>';
	}//end if
	echo '</channel></rss>';
?>