<?php
/**
 * This file is part of Helios Calendar, it's use is governed by the Helios Calendar Software License Agreement.
 *
 * @author Refresh Web Development, LLC.
 * @link http://www.refreshmy.com
 * @copyright (C) 2004-2011 Refresh Web Development
 * @license http://www.helioscalendar.com/license.html
 * @package Helios Calendar
 */
	$isAction = 1;
	include('../includes/include.php');
	include('../' . $hc_langPath . $_SESSION['LangSet'] . '/config.php');
	include('../' . $hc_langPath . $_SESSION['LangSet'] . '/public/rss.php');
	
	$hourOffset = date("G") + ($hc_cfg35);
	$tzOffset = date("O") + ($hc_cfg35 * 100);
	$numFormat = false;
	$feedName = $hc_lang_rss['FeedLabelCustom'];

	if($tzOffset == 0){
		$tzOffset = "+0000";
	} elseif($tzOffset < 0){
		if(strlen($tzOffset) < 5){
			$tzOffset = ltrim($tzOffset,"-");
			$tzOffset = "-0" . $tzOffset;
		}//end if
	} elseif($tzOffset > 0) {
		$tzOffset = (strlen($tzOffset) < 4) ? '+0' . $tzOffset : '+' . $tzOffset;
	}//end if
	
	$dateRange = "e.StartDate >= '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "'";
	if(isset($_GET['d']) && is_numeric($_GET['d'])){
		if($_GET['d'] == 1){
			$dateRange = "e.StartDate = '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "'";
		} else if($_GET['d'] == 2){
			$dateRange = "e.StartDate Between '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d")+7,date("Y"))) . "'";
		} else if($_GET['d'] == 3) {
			$dateRange = "e.StartDate Between '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m")+1,date("d"),date("Y"))) . "'";
		}//end if
	}//end if

	$queryCats = $queryCity = $cityNames = '';
	$catIDs = "0";
	if(isset($_GET['l'])){
		$catID = explode(",", $_GET['l']);
		foreach ($catID as $val){
			$catIDs .= (is_numeric($val)) ? ',' . cleanXMLChars(strip_tags(cIn($val))) : '';
		}//end for
		$queryCats = " AND c.PkID IN (" . cIn($catIDs) . ")";
	}//end if
	
	if(isset($_GET['c'])){
		$cityName = explode(",", $_GET['c']);
		foreach ($cityName as $val){
			$cityNames .= ($cityNames != '') ? "," . "'" . strip_tags(cIn($val)) . "'" : "'" . strip_tags(cIn($val)) . "'";
		}//end for
		if($cityNames != ""){
			$queryCity = " AND (e.LocationCity IN (" . $cityNames . ") OR l.City IN (" . $cityNames . "))";
		}//end if
	}//end if

	if($cityNames == '' && $catIDs == '0'){
		header("Location: " . CalRoot . "/rss/");
		exit();
	}//end if

	$query = "SELECT DISTINCT e.PkID, e.Title, e.Description, e.StartDate, e.StartTime, e.SeriesID
			FROM " . HC_TblPrefix . "events e
				LEFT JOIN " . HC_TblPrefix . "eventcategories ec ON (e.PkID = ec.EventID)
				LEFT JOIN " . HC_TblPrefix . "categories c ON (ec.CategoryID = c.PkID)
				LEFT JOIN " . HC_TblPrefix . "locations l ON (e.LocID = l.PkID)
			WHERE e.IsActive = 1 AND
				e.IsApproved = 1 AND
				" . $dateRange . " AND
				c.IsActive = 1
			" . $queryCats . "
			" . $queryCity . "
			ORDER BY e.StartDate, e.TBD, e.StartTime
			LIMIT " . $hc_cfg2 * 2;
	
	header('Content-Type:application/rss+xml; charset=' . $hc_lang_config['CharSet']);
	echo "<?xml version=\"1.0\" encoding=\"" . $hc_lang_config['CharSet'] . "\"?>";
	echo "\n<?xml-stylesheet type=\"text/css\" href=\"" . CalRoot . "/css/rss.css\"?>";
	echo "\n" . '<!-- Generated by Helios Calendar ' . $hc_cfg49 . ' ' . date("\\o\\n Y-m-d \\a\\t H:i:s") . ' local time. -->';
	echo "\n" . '<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">';
	echo "\n" . '<channel>';
	echo "\n" . '<title>' . $feedName . ' - ' . CalName . '</title>';
	echo "\n" . '<link>' . CalRoot . '/</link>';
	echo "\n" . '<copyright>Copyright 2004-' . date("Y") . ' Refresh Web Development, LLC.</copyright>';
	echo "\n" . '<generator>http://www.HeliosCalendar.com</generator>';
	echo "\n" . '<docs>' . CalRoot . '&#47;index.php&#63;com=rss</docs>';
	echo "\n" . '<description>Upcoming Event Information From ' . CalName . '</description>';

	$result = doQuery($query);
	if(hasRows($result)){
		$hideSeries[] = array();
		$cnt = 0;
		while($row = mysql_fetch_row($result)){
			if($cnt >= $hc_cfg2){break;}//end if

			if($row[5] == '' || !in_array($row[5], $hideSeries)){
				echo "\n" . '<item>';
				echo "\n" . '<title>';
				if($numFormat){
					echo ($cnt < 10) ? sprintf("%02d ) ", $cnt+1) : ($cnt+1) . ') ';
				}//end if
				echo cleanXMLChars(stampToDate(cOut($row[3]), $hc_cfg24)) . " - " . html_entity_decode(cleanXMLChars(cOut(strip_tags($row[1])))) . '</title>';
				echo "\n" . '<link><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . ']]></link>';
				echo "\n" . '<description>' . html_entity_decode(cleanXMLChars(cOut($row[2]))) . '</description>';
				echo "\n" . '<comments><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . '#cmnts' . ']]></comments>';
				echo "\n" . '<guid>' . CalRoot . '/index.php&#63;com=detail&amp;eID=' . $row[0] . '</guid>';
				echo "\n" . '<pubDate>' . cleanXMLChars(stampToDate($row[3] . ' ' . $row[4], "%a, %d %b %Y %H:%M:%S") . ' ' . $tzOffset) . '</pubDate>';
				echo "\n" . '</item>';
				++$cnt;
			}//end if

			if($hc_cfg33 == 0 && $row[5] != '' && (!in_array($row[5], $hideSeries))){
				$hideSeries[] = $row[5];
			}//end if
		}//end while
	} else {
		echo "\n" . '<item>';
		echo "\n" . '<title>' . $hc_lang_rss['RSSNoEvents'] . '</title>';
		echo "\n" . '<link>' . CalRoot . '/</link>';
		echo "\n" . '<description>' . $hc_lang_rss['RSSMoreInfo'] . '</description>';
		echo "\n" . '</item>';
	}//end if
	echo "\n</channel>\n</rss>";
?>