<?php
/**
 * This file is part of Helios Calendar, it's use is governed by the Helios Calendar Software License Agreement.
 *
 * @author Refresh Web Development, LLC.
 * @link http://www.refreshmy.com
 * @copyright (C) 2004-2011 Refresh Web Development
 * @license http://www.helioscalendar.com/license.html
 * @package Helios Calendar
 */
	$isAction = 1;
	include('../includes/include.php');
	include('../' . $hc_langPath . $_SESSION['LangSet'] . '/config.php');
	include('../' . $hc_langPath . $_SESSION['LangSet'] . '/public/rss.php');
	
	$hourOffset = date("G") + ($hc_cfg35);
	$tzOffset = date("O") + ($hc_cfg35 * 100);
	$numFormat = false;
	$sID = (isset($_GET['s']) && is_numeric($_GET['s'])) ? cIn($_GET['s']) : 0;
	$curCache = date("Ymd", mktime($hourOffset,0,0,date("m"),date("d"),date("Y")));
	$feedName = $hc_lang_rss['FeedLabel' . $sID];
	
	header('Content-Type:application/rss+xml; charset=' . $hc_lang_config['CharSet']);
	echo "<?xml version=\"1.0\" encoding=\"" . $hc_lang_config['CharSet'] . "\"?>";
	echo "\n<?xml-stylesheet type=\"text/css\" href=\"" . CalRoot . "/css/rss.css\"?>";
	
	if(!file_exists(realpath('../cache/rss' . $curCache . '_' . $sID . '.php'))){
		if(count(glob('../cache/rss*_' . $sID . '.*')) > 0){
			foreach(glob('../cache/rss*_' . $sID . '.*') as $filename){
				unlink($filename);
			}//end foreach
		}//end if

		if($tzOffset == 0){
			$tzOffset = "+0000";
		} elseif($tzOffset < 0){
			if(strlen($tzOffset) < 5){
				$tzOffset = ltrim($tzOffset,"-");
				$tzOffset = "-0" . $tzOffset;
			}//end if
		} elseif($tzOffset > 0) {
			$tzOffset = (strlen($tzOffset) < 4) ? '+0' . $tzOffset : '+' . $tzOffset;
		}//end if

		$dateRange = "e.StartDate >= '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "'";
		if(isset($_GET['d']) && is_numeric($_GET['d'])){
			if($_GET['d'] == 1){
				$dateRange = "e.StartDate = '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "'";
			} else if($_GET['d'] == 2){
				$dateRange = "e.StartDate Between '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d")+7,date("Y"))) . "'";
			} else if($_GET['d'] == 3) {
				$dateRange = "e.StartDate Between '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m")+1,date("d"),date("Y"))) . "'";
			}//end if
		}//end if

		$query = "SELECT DISTINCT e.PkID, e.Title, e.Description, e.StartDate, e.StartTime, e.SeriesID
				FROM " . HC_TblPrefix . "events e WHERE e.IsActive = 1 AND e.IsApproved = 1 AND " . $dateRange;
		switch($sID){
			case 0:
				$query .= " ORDER BY e.StartDate, e.TBD, e.StartTime LIMIT " . $hc_cfg2 * 2;
				break;
			case 1:
				$query .= " ORDER BY e.PublishDate DESC, e.StartDate, e.StartTime LIMIT " . $hc_cfg2 * 2;
				break;
			case 2:
				$query .= " ORDER BY e.Views DESC, e.StartDate, e.StartTime LIMIT " . $hc_cfg2 * 2;
				break;
			case 3:
				$query .= " AND e.IsBillboard = 1 ORDER BY e.StartDate, e.TBD, e.StartTime LIMIT " . $hc_cfg2 * 2;
				break;
			case 4:
				$numFormat = true;
				$query = "SELECT DISTINCT e.PkID, e.Title, e.Description, e.StartDate, e.StartTime, e.SeriesID, COUNT(c.EntityID) as Cnt
						FROM " . HC_TblPrefix . "comments c
							LEFT JOIN " . HC_TblPrefix . "events e ON (e.PkID = c.EntityID)
						WHERE
							c.IsActive = 1 AND
							e.IsActive = 1 AND
							e.StartDate >= '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "'
						GROUP BY c.EntityID
						ORDER BY Cnt DESC
						LIMIT " . $hc_cfg2 * 2;
				break;
		}//end switch

		rebuildRSS($sID,$query);
	}//end if
	include('../cache/rss' . $curCache . '_' . $sID . '.php');
	
	function rebuildRSS($sID, $query){
		global $hc_lang_rss, $hc_cfg2, $hc_cfg24, $hc_cfg33, $hc_cfg49, $feedName, $curCache, $tzOffset, $numFormat;
		ob_start();
		$fp = fopen('../cache/rss' . $curCache . '_' . $sID . '.php', 'w');
		fwrite($fp, "\n" . '<!-- Generated by Helios Calendar ' . $hc_cfg49 . ' ' . date("\\o\\n Y-m-d \\a\\t H:i:s") . ' local time. -->');
		fwrite($fp, "\n" . '<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">');
		fwrite($fp, "\n" . '<channel>');
		fwrite($fp, "\n" . '<title>' . $feedName . ' - ' . CalName . '</title>');
		fwrite($fp, "\n" . '<link>' . CalRoot . '/</link>');
		fwrite($fp, "\n" . '<copyright>Copyright 2004-' . date("Y") . ' Refresh Web Development, LLC.</copyright>');
		fwrite($fp, "\n" . '<generator>http://www.HeliosCalendar.com</generator>');
		fwrite($fp, "\n" . '<docs>' . CalRoot . '&#47;index.php&#63;com=rss</docs>');
		fwrite($fp, "\n" . '<description>Upcoming Event Information From ' . CalName . '</description>');

		$result = doQuery($query);
		if(hasRows($result)){
			$hideSeries[] = array();
			$cnt = 0;
			while($row = mysql_fetch_row($result)){
				if($cnt >= $hc_cfg2){break;}//end if

				if($row[5] == '' || !in_array($row[5], $hideSeries)){
					echo "\n" . '<item>';
					echo "\n" . '<title>';
					if($numFormat){
						echo ($cnt < 10) ? sprintf("%02d ) ", $cnt+1) : ($cnt+1) . ') ';
					}//end if
					echo cleanXMLChars(stampToDate(cOut($row[3]), $hc_cfg24)) . " - " . html_entity_decode(cleanXMLChars(cOut(strip_tags($row[1])))) . '</title>';
					echo "\n" . '<link><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . ']]></link>';
					echo "\n" . '<description>' . html_entity_decode(cleanXMLChars(cOut($row[2]))) . '</description>';
					echo "\n" . '<comments><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . '#cmnts' . ']]></comments>';
					echo "\n" . '<guid>' . CalRoot . '/index.php&#63;com=detail&amp;eID=' . $row[0] . '</guid>';
					echo "\n" . '<pubDate>' . cleanXMLChars(stampToDate($row[3] . ' ' . $row[4], "%a, %d %b %Y %H:%M:%S") . ' ' . $tzOffset) . '</pubDate>';
					echo "\n" . '</item>';
					++$cnt;
				}//end if

				if($hc_cfg33 == 0 && $row[5] != '' && (!in_array($row[5], $hideSeries))){
					$hideSeries[] = $row[5];
				}//end if
			}//end while
		} else {
			echo "\n" . '<item>';
			echo "\n" . '<title>' . $hc_lang_rss['RSSNoEvents'] . '</title>';
			echo "\n" . '<link>' . CalRoot . '/</link>';
			echo "\n" . '<description>' . $hc_lang_rss['RSSMoreInfo'] . '</description>';
			echo "\n" . '</item>';
		}//end if
		echo "\n</channel>\n</rss>";

		fwrite($fp, ob_get_contents());
		fclose($fp);
		ob_end_clean();
	}//end if?>