<?php
/**
 * This file is part of Helios Calendar, it's use is governed by the Helios Calendar Software License Agreement.
 *
 * @author Refresh Web Development, LLC.
 * @link http://www.refreshmy.com
 * @copyright (C) 2004-2011 Refresh Web Development
 * @license http://www.helioscalendar.com/license.html
 * @package Helios Calendar
 */
	$isAction = 1;
	include('../includes/include.php');
	include('../' . $hc_langPath . $_SESSION['LangSet'] . '/config.php');
	include('../' . $hc_langPath . $_SESSION['LangSet'] . '/public/rss.php');
	
	$hourOffset = date("G") + ($hc_cfg35);
	$tzOffset = date("O") + ($hc_cfg35 * 100);
	$lID = (isset($_GET['lID']) && is_numeric($_GET['lID'])) ? cIn($_GET['lID']) : -1;
	
	if($tzOffset == 0){
		$tzOffset = "+0000";
	} elseif($tzOffset < 0){
		if(strlen($tzOffset) < 5){
			$tzOffset = ltrim($tzOffset,"-");
			$tzOffset = "-0" . $tzOffset;
		}//end if
	} elseif($tzOffset > 0) {
		$tzOffset = (strlen($tzOffset) < 4) ? '+0' . $tzOffset : '+' . $tzOffset;
	}//end if
	
	$result = doQuery("SELECT * FROM " . HC_TblPrefix . "locations WHERE PkID = '" . $lID . "' AND IsActive = 1");
	$locName = (hasRows($result)) ? mysql_result($result,0,1) : '';
	
	header('Content-Type:application/rss+xml; charset=' . $hc_lang_config['CharSet']);
	echo "<?xml version=\"1.0\" encoding=\"" . $hc_lang_config['CharSet'] . "\"?>";
	echo "\n<?xml-stylesheet type=\"text/css\" href=\"" . CalRoot . "/css/rss.css\"?>";
	
	$query = "	SELECT e.PkID, e.Title, e.Description, e.StartDate, e.StartTime, e.SeriesID
				FROM " . HC_TblPrefix . "events e
					LEFT JOIN " . HC_TblPrefix . "eventcategories ec ON (e.PkID = ec.EventID)
					LEFT JOIN " . HC_TblPrefix . "categories c ON (ec.CategoryID = c.PkID)
				WHERE e.IsActive = 1 AND 
					e.IsApproved = 1 AND 
					e.StartDate >= '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND
					c.IsActive = 1 AND 
					e.LocID = '" . $lID . "'
				GROUP BY e.PkID
				ORDER BY e.StartDate, e.TBD, e.StartTime
				LIMIT " . $hc_cfg2 * 2;
	$feedName = $locName . " : Location Events";

	echo "\n" . '<!-- Generated by Helios Calendar ' . $hc_cfg49 . ' ' . date("\\o\\n Y-m-d \\a\\t H:i:s") . ' local time. -->';
	echo "\n" . '<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">';
	echo "\n" . '<channel>';
	echo "\n" . '<title>' . $feedName . ' - ' . CalName . '</title>';
	echo "\n" . '<link>' . CalRoot . '/</link>';
	echo "\n" . '<copyright>Copyright 2004-' . date("Y") . ' Refresh Web Development, LLC.</copyright>';
	echo "\n" . '<generator>http://www.HeliosCalendar.com</generator>';
	echo "\n" . '<docs>' . CalRoot . '&#47;index.php&#63;com=rss</docs>';
	echo "\n" . '<description>Upcoming Event Information From ' . CalName . '</description>';
	
	$result = doQuery($query);
	
	if(hasRows($result)){
		$cnt = 0;
		while($row = mysql_fetch_row($result)){
			if($cnt >= $hc_cfg2){break;}
			echo "\n" . '<item>';
			echo "\n" . '<title>' . cleanXMLChars(stampToDate(cOut($row[3]), $hc_cfg24)) . " - " . html_entity_decode(cleanXMLChars(cOut($row[1]))) . '</title>';
			echo "\n" . '<link><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . ']]></link>';
			echo "\n" . '<description>' . html_entity_decode(cleanXMLChars(cOut($row[2]))) . '</description>';
			echo "\n" . '<comments><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . '#cmnts' . ']]></comments>';
			echo "\n" . '<guid>' . CalRoot . '/index.php&#63;com=detail&amp;eID=' . $row[0] . '</guid>';
			echo "\n" . '<pubDate>' . cleanXMLChars(stampToDate($row[3] . ' ' . $row[4], "%a, %d %b %Y %H:%M:%S") . ' ' . $tzOffset) . '</pubDate>';
			echo "\n" . '</item>';
			++$cnt;
		}//end while
	} else {
		echo "\n" . '<item>';
		echo "\n" . '<title>' . $hc_lang_rss['RSSNoEvents'] . '</title>';
		echo "\n" . '<link>' . CalRoot . '/</link>';
		echo "\n" . '<description>' . $hc_lang_rss['RSSMoreInfo'] . '</description>';
		echo "\n" . '</item>';
	}//end if
	echo '</channel></rss>';
?>