<?php
/*
	Helios Calendar
	Copyright (C) 2004-2010 Refresh Web Development, LLC. [www.RefreshMy.com]

	This file is part of Helios Calendar, it's usage is governed by
	the Helios Calendar SLA found at www.HeliosCalendar.com/license.html
*/
	$isAction = 1;
	include('../includes/include.php');
	include('../' . $hc_langPath . $_SESSION[$hc_cfg00 . 'LangSet'] . '/config.php');
	include('../' . $hc_langPath . $_SESSION[$hc_cfg00 . 'LangSet'] . '/public/rss.php');
	
	$hourOffset = date("G") + ($hc_cfg35);
	$tzOffset = date("O") + ($hc_cfg35 * 100);
	$lID = (isset($_GET['lID']) && is_numeric($_GET['lID'])) ? cIn($_GET['lID']) : -1;
	
	if($tzOffset == 0){
		$tzOffset = "+0000";
	} elseif($tzOffset < 0){
		if(strlen($tzOffset) < 5){
			$tzOffset = ltrim($tzOffset,"-");
			$tzOffset = "-0" . $tzOffset;
		}//end if
	} elseif($tzOffset > 0) {
		$tzOffset = (strlen($tzOffset) < 4) ? '+0' . $tzOffset : '+' . $tzOffset;
	}//end if
	
	$result = doQuery("SELECT * FROM " . HC_TblPrefix . "locations WHERE PkID = '" . $lID . "' AND IsActive = 1");
	$locName = (hasRows($result)) ? mysql_result($result,0,1) : '';
	
	header('Content-Type:application/rss+xml; charset=' . $hc_lang_config['CharSet']);
	echo "<?xml version=\"1.0\" encoding=\"" . $hc_lang_config['CharSet'] . "\"?>";
	echo "\n<?xml-stylesheet type=\"text/css\" href=\"" . CalRoot . "/css/rss.css\"?>";
	
	$query = "	SELECT e.PkID, e.Title, e.Description, e.StartDate, e.StartTime, e.SeriesID
				FROM " . HC_TblPrefix . "events e
					LEFT JOIN " . HC_TblPrefix . "eventcategories ec ON (e.PkID = ec.EventID)
					LEFT JOIN " . HC_TblPrefix . "categories c ON (ec.CategoryID = c.PkID)
				WHERE e.IsActive = 1 AND 
					e.IsApproved = 1 AND 
					e.StartDate >= '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND
					c.IsActive = 1 AND 
					e.LocID = '" . $lID . "'
				GROUP BY e.PkID
				ORDER BY e.StartDate, e.TBD, e.StartTime
				LIMIT " . $hc_cfg2 * 2;
	$feedName = $locName . " : Location Events";

	echo '<!-- Generated by Helios Calendar ' . $hc_cfg49 . ' ' . date("\\o\\n Y-m-d \\a\\t H:i:s") . ' local time. -->';
	echo '<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">';
	echo '<channel>';
	echo '<title>' . $feedName . ' - ' . CalName . '</title>';
	echo '<link>' . CalRoot . '/</link>';
	echo '<copyright>Copyright 2004-' . date("Y") . ' Refresh Web Development, LLC.</copyright>';
	echo '<generator>http://www.HeliosCalendar.com</generator>';
	echo '<docs>' . CalRoot . '&#47;index.php&#63;com=rss</docs>';
	echo '<description>Upcoming Event Information From ' . CalName . '</description>';
	
	$result = doQuery($query);
	
	if(hasRows($result)){
		$cnt = 0;
		while($row = mysql_fetch_row($result)){
			if($cnt >= $hc_cfg2){break;}

			echo '<item>';
			echo '<title>' . cleanXMLChars(stampToDate(cOut($row[3]), $hc_cfg24)) . " - " . html_entity_decode(cleanXMLChars(cOut($row[1])));
			echo '</title>';
			echo '<link><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . ']]></link>';
			echo '<description>' . cleanXMLChars(cOut($row[2])) . '</description>';
			echo '<comments><![CDATA[' . CalRoot . '/index.php?com=detail&eID=' . $row[0] . '#cmnts' . ']]></comments>';
			echo '<guid>' . CalRoot . '/index.php&#63;com=detail&amp;eID=' . $row[0] . '</guid>';
			$dateParts = explode("-",$row[3]);
			$timeParts = explode(":",$row[4]);
			$hour = (isset($timeParts[1])) ? $timeParts[0] : 0;
			$min = (isset($timeParts[1])) ? $timeParts[1] : 0;
			$sec = (isset($timeParts[1])) ? $timeParts[2] : 0;
			echo '<pubDate>' . cleanXMLChars(date("D\, d M Y H:i:s", mktime($hour,$min,$sec,$dateParts[1],$dateParts[2],$dateParts[0])) . ' ' . $tzOffset) . '</pubDate>';
			echo '</item>';
			++$cnt;
		}//end while
	} else {
		echo '<item>';
		echo '<title>' . $hc_lang_rss['RSSNoEvents'] . '</title>';
		echo '<link>' . CalRoot . '/</link>';
		echo '<description>' . $hc_lang_rss['RSSMoreInfo'] . '</description>';
		echo '</item>';
	}//end if
	echo '</channel></rss>';
?>