// HE lang variables by Liron Newman, http://eesh.net

tinyMCE.addToLang('',{
table_desc : 'מכניס טבל&auml; חדש&auml;',
table_insert_row_before_desc : '&auml;כנס ש&aring;ר&auml; לפני',
table_insert_row_after_desc : '&auml;כנס ש&aring;ר&auml; אחרי',
table_delete_row_desc : 'מחק ש&aring;ר&auml;',
table_insert_col_before_desc : '&auml;כנס ט&aring;ר לפני',
table_insert_col_after_desc : '&auml;כנס ט&aring;ר אחרי',
table_delete_col_desc : '&auml;סר ט&aring;ר',
insert_table_title : '&auml;כנס/שנ&auml; טבל&auml;',
insert_table_width : 'ר&aring;חב',
insert_table_height : 'ג&aring;ב&auml;',
insert_table_cols : 'ט&aring;רים',
insert_table_rows : 'ש&aring;ר&aring;ת',
insert_table_cellspacing : 'רי&aring;&aring;ח בין תאים',
insert_table_cellpadding : 'ריפ&aring;ד תאים',
insert_table_border : 'גב&aring;ל',
insert_table_align : 'ייש&aring;ר',
insert_table_align_default : 'ברירת מחדל',
insert_table_align_left : 'שמאל',
insert_table_align_right : 'ימין',
insert_table_align_middle : 'מרכז',
insert_table_class : 'מחלק&auml;',
table_row_title : 'מאפייני ש&aring;רת טבל&auml;',
table_cell_title : 'מאפייני תא טבל&auml;',
table_row_desc : 'מאפייני ש&aring;רת טבל&auml;',
table_cell_desc : 'מאפייני תא טבל&auml;',
insert_table_valign : 'ייש&aring;ר אנכי',
insert_table_align_top : 'למעל&auml;',
insert_table_align_bottom : 'למט&auml;',
table_props_desc : 'מאפייני טבל&auml;',
table_bordercolor : '&ouml;בע גב&aring;ל',
table_bgcolor : '&ouml;בע רקע',
table_merge_cells_title : 'מזג תאים בטבל&auml;',
table_split_cells_desc : 'פ&ouml;ל תאים בטבל&auml;',
table_merge_cells_desc : 'מזג תאים בטבל&auml;',
table_cut_row_desc : 'גז&aring;ר ש&aring;ר&auml; מ&auml;טבל&auml;',
table_copy_row_desc : '&auml;עתק ש&aring;ר&auml; מ&auml;טבל&auml;',
table_paste_row_before_desc : '&auml;דבק ש&aring;ר&auml; לטבל&auml; לפני',
table_paste_row_after_desc : '&auml;דבק ש&aring;ר&auml; לטבל&auml; אחרי',
table_insert_desc : '&auml;כנס טבל&auml; חדש&auml;'
});
