<?php
/*
	Helios Calendar - Professional Event Management System
	Copyright © 2004-2009 Refresh Web Development [www.RefreshMy.com]
	
	For the most recent version, visit the Helios Calendar website:
	[www.HeliosCalendar.com]
	
	This file is part of Helios Calendar, usage governed by 
	the Helios Calendar SLA found at www.HeliosCalendar.com/license.index.html
*/
	include('includes/include.php');
	include($hc_langPath . $_SESSION[$hc_cfg00 . 'LangSet'] . '/config.php');
	include($hc_langPath . $_SESSION[$hc_cfg00 . 'LangSet'] . '/public/rss.php');
	
	$hourOffset = date("G") + ($hc_cfg35);
	$tzOffset = date("O") + ($hc_cfg35 * 100);
	$lID = (isset($_GET['lID']) && is_numeric($_GET['lID'])) ? $_GET['lID'] : 0;
	
	if($tzOffset == 0){
		$tzOffset = "+0000";
	} elseif($tzOffset < 0){
		if(strlen($tzOffset) < 5){
			$tzOffset = ltrim($tzOffset,"-");
			$tzOffset = "-0" . $tzOffset;
		}//end if
	} elseif($tzOffset > 0) {
		$tzOffset = (strlen($tzOffset) < 4) ? '+0' . $tzOffset : '+' . $tzOffset;
	}//end if
	
	$result = doQuery("SELECT * FROM " . HC_TblPrefix . "locations WHERE PkID = '" . $lID . "' AND IsActive = 1");
	$locName = (hasRows($result)) ? mysql_result($result,0,1) : '';
	
	header('Content-Type:application/rss+xml; charset=' . $hc_lang_config['CharSet']);
	echo "<?xml version=\"1.0\" encoding=\"" . $hc_lang_config['CharSet'] . "\"?>";
	echo "\n<?xml-stylesheet type=\"text/css\" href=\"" . CalRoot . "/css/rss.css\"?>";
	
	$query = "	SELECT distinct e.*
				FROM " . HC_TblPrefix . "events e
					LEFT JOIN " . HC_TblPrefix . "eventcategories ec ON (e.PkID = ec.EventID)
					LEFT JOIN " . HC_TblPrefix . "categories c ON (ec.CategoryID = c.PkID)
				WHERE e.IsActive = 1 AND 
					e.IsApproved = 1 AND 
					e.StartDate >= '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND
					c.IsActive = 1 AND 
					e.LocID = '" . $lID . "'
				ORDER BY e.StartDate, e.TBD, e.StartTime
				LIMIT " . $hc_cfg2 * 2;
	$feedName = $locName . " : Location Events";?>
	
<!-- Generated by Helios Calendar <?php echo $hc_cfg49;?> <?php echo date("\\o\\n Y-m-d \\a\\t H:i:s");?> <?php echo "\n";?> http://www.HeliosCalendar.com -->
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title><?php echo $feedName . " - " . CalName;?></title>
    <link><?php echo CalRoot;?>/</link>
    <copyright>Copyright 2004-<?php echo date("Y");?> Refresh Web Development LLC</copyright>
	<generator>http://www.HeliosCalendar.com</generator>
	<docs><?php echo CalRoot;?>&#47;index.php&#63;com=rss</docs>
	<description>Upcoming Event Information From <?php echo CalName;?></description>
<?php	$result = doQuery($query);
		
		if(hasRows($result)){
			$cnt = 0;
			while($row = mysql_fetch_row($result)){	
				if($cnt >= $hc_cfg2){break;}?>
				<item>
			      <title><?php echo cleanXMLChars(stampToDate(cOut($row[9]), $hc_cfg24)) . " - " . html_entity_decode(cleanXMLChars(cOut($row[1])));?></title>
			      <link><![CDATA[<?php echo CalRoot . "/index.php?com=detail&eID=" . $row[0];?>]]></link>
			      <description><?php echo cleanXMLChars(cOut($row[8]));?></description>
			      <comments><![CDATA[<?php echo CalRoot . "/index.php?com=detail&eID=" . $row[0] . "#comments";?>]]></comments>
			      <guid><?php echo CalRoot . "/index.php&#63;com=detail&amp;eID=" . $row[0];?></guid>
				  <?php
				  	$dateParts = explode("-",$row[9]);
				  	$timeParts = explode(":",$row[10]);	
				  	$hour = (isset($timeParts[1])) ? $timeParts[0] : 0;
				  	$min = (isset($timeParts[1])) ? $timeParts[1] : 0;
				  	$sec = (isset($timeParts[1])) ? $timeParts[2] : 0;?>
				  <pubDate><?php echo cleanXMLChars(date("D\, d M Y H:i:s", mktime($hour,$min,$sec,$dateParts[1],$dateParts[2],$dateParts[0])) . ' ' . $tzOffset);?></pubDate>
			    </item>
	<?php 		$cnt++;
			}//end while	
		} else {	?>
			<item>
		      <title><?php echo $hc_lang_rss['RSSNoEvents'];?></title>
		      <link><?php echo CalRoot;?>/</link>
		      <description><?php echo $hc_lang_rss['RSSMoreInfo'];?></description>
		    </item>
<?php 	}//end if	?>
  </channel>
</rss>