<?php
/*
	Helios Calendar - Professional Event Management System
	Copyright © 2007 Refresh Web Development [http://www.refreshwebdev.com]
	
	Developed By: Chris Carlevato <chris@refreshwebdev.com>
	
	For the most recent version, visit the Helios Calendar website:
	[http://www.helioscalendar.com]
	
	License Information is found in docs/license.html
*/
	include('includes/include.php');
	
	$result = doQuery("SELECT SettingValue FROM " . HC_TblPrefix . "settings WHERE PkID IN (2,14,33,35)");
	$maxShow = cOut(mysql_result($result,0,0));
	$dateFormat = cOut(mysql_result($result,1,0));
	$series = cOut(mysql_result($result,2,0));
	$hc_timezoneOffset = cOut(mysql_result($result,3,0));
	
	$hourOffset = date("G");
	if($hc_timezoneOffset > 0){
		$hourOffset = $hourOffset + abs($hc_timezoneOffset);
	} else {
		$hourOffset = $hourOffset - abs($hc_timezoneOffset);
	}//end if
	
	$lID = 0;
	if(isset($_GET['lID']) && is_numeric($_GET['lID'])){
		$lID = $_GET['lID'];
	}//end if
	
	$result = doQuery("SELECT * FROM " . HC_TblPrefix . "locations WHERE PkID = '" . $lID . "' AND IsActive = 1");
	$locName = "";
	if(hasRows($result)){
		$locName = mysql_result($result,0,1);
	}//end if
	
	header ('Content-Type:text/xml; charset=utf-8');
	echo "<?xml-stylesheet type=\"text/css\" href=\"" . CalRoot . "/css/rss.css\"?>";	
	$query = "	SELECT distinct e.*
				FROM " . HC_TblPrefix . "events e
					LEFT JOIN " . HC_TblPrefix . "eventcategories ec ON (e.PkID = ec.EventID)
					LEFT JOIN " . HC_TblPrefix . "categories c ON (ec.CategoryID = c.PkID)
				WHERE e.IsActive = 1 AND 
					e.IsApproved = 1 AND 
					e.StartDate >= '" . date("Y-m-d",mktime($hourOffset,date("i"),date("s"),date("m"),date("d"),date("Y"))) . "' AND
					c.IsActive = 1 AND 
					e.LocID = '" . $lID . "'
				ORDER BY e.StartDate, e.TBD, e.StartTime
				LIMIT " . $maxShow * 2;
	$feedName = $locName . " : Location Events";?>
	
<!-- Generated by Helios Calendar <?php echo HC_Version;?> <?php echo date("\\o\\n Y-m-d \\a\\t H:i:s");?> <?php echo "\n";?> http://www.HeliosCalendar.com -->
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title><?php echo $feedName . " - " . CalName;?></title>
    <link><?php echo CalRoot;?>/</link>
    <language>en-us</language>
    <copyright>Copyright 2004-<?php echo date("Y");?> Refresh Web Development LLC</copyright>
	<generator>http://www.HeliosCalendar.com</generator>
	<docs><?php echo CalRoot;?>&#47;index.php&#63;com=rss</docs>
	<description>Upcoming Event Information From The <?php echo CalName;?></description>
<?php	$result = doQuery($query);
		
		if(hasRows($result)){
			
			$cnt = 0;
			while($row = mysql_fetch_row($result)){	
				if($cnt >= $maxShow){break;}//end if	?>
				<item>
			      <title><?php echo stampToDate(cOut($row[9]), $dateFormat) . " - " . strip_tags(htmlspecialchars(cOut(str_replace("?", "&#63;", $row[1]))));?></title>
			      <link><?php echo CalRoot . "/index.php&#63;com=detail&amp;eID=" . $row[0];?></link>
			      <description><?php echo htmlspecialchars(cOut(strip_tags(str_replace("?", "&#63;", $row[8]))));?></description>
				  <guid><?php echo CalRoot . "/index.php&#63;com=detail&amp;eID=" . $row[0];?></guid>
				  <pubDate><?php echo stampToDate(cOut($row[9]), "r");?></pubDate>
			    </item>
	<?php 		$cnt++;
			}//end while	
		} else {	?>
			<item>
		      <title>There Are No Upcoming Events Available For This Location</title>
		      <link><?php echo CalRoot;?>/</link>
		      <description>Visit the <?php echo CalName;?> for more information.</description>
		    </item>
<?php 	}//end if	?>
  </channel>
</rss>