<?php
/**
 * This file is part of Helios Calendar, it's use is governed by the Helios Calendar Software License Agreement.
 *
 * @author Refresh Web Development LLC
 * @link http://www.refreshmy.com
 * @copyright (C) 2004-2011 Refresh Web Development
 * @license http://www.helioscalendar.com/license.html
 * @package Helios Calendar
 */
/*
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	|	Modifying or in anyway altering source code contained in this file is 	|
	|	not permitted and violates the Helios Calendar Software License Agreement	|
	|	DO NOT edit or reverse engineer any source code or files with this notice	|
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
	if(!isset($_SESSION['license']) || $_SESSION['license'] == false || !isset($_SESSION['review']) || $_SESSION['review'] == false){
		hc_fail();
	} else {
		if(!isset($_POST['liccode'])){
			echo '
		<p>
			To retrieve your license code from your member account click "Refresh Members Site" to the right.
		</p>
		<form name="frm" id="frm" method="post" action="'.CalRoot.'/setup/index.php?step=3" onsubmit="return (document.getElementById(\'liccode\').value != \'\') ? true : false;">
		<fieldset>
			<label for="liccode">License Code:</label>
			<input size="50" type="text" name="liccode" id="liccode" value="" autofocus="autofocus" required="required" />
		</fieldset>
		<input type="submit" name="submit" id="submit" value="Confirm License" />
		</form>';
		} else {
			eval(base64_decode('LypJZiB5b3UgYXJlIHJlYWRpbmcgdGhpcyB5b3UgaGF2ZSB2aW9sYXRlZCB0aGUgSGVsaW9zIENhbGVuZGFyIFNvZnR3YXJlIExpY2Vuc2UgQWdyZWVtZW50Ki8NCmlmKCRfUE9TVFsnbGljY29kZSddID09ICJsb2NhbGhvc3QiICYmICRfU0VSVkVSWydIVFRQX0hPU1QnXSA9PSAibG9jYWxob3N0IiAmJiBzdHJwb3MoQ2FsUm9vdCwnbG9jYWxob3N0JykgIT09IGZhbHNlKXsNCgkkX1NFU1NJT05bJ3ZhbGlkJ10gPSB0cnVlOw0KCSRfU0VTU0lPTlsncmVnY29kZSddID0gImxvY2FsaG9zdF9vbmx5IjsNCgkkX1NFU1NJT05bJ3JlZ25hbWUnXSA9ICJEZXZlbG9wZXIiOw0KCSRfU0VTU0lPTlsncmVndXJsJ10gPSAibG9jYWxob3N0IjsNCgkkX1NFU1NJT05bJ3JlZ2VtYWlsJ10gPSAic3VwcG9ydEBoZWxpb3NjYWxlbmRhci5jb20iOw0KCWVjaG8gJw0KCQk8ZmllbGRzZXQ+DQoJCQk8cD4NCgkJCQlZb3VyIGxvY2FsaG9zdCBpbnN0YWxsYXRpb24gb2YgSGVsaW9zIENhbGVuZGFyIGhhcyBiZWVuIHZhbGlkYXRlZC4NCgkJCTwvcD4NCgkJCTxwPg0KCQkJCVRoaXMgaW5zdGFsbGF0aW9uIHdpbGwgb25seSBiZSB2aXNpYmxlIGZyb20gdGhlIGxvY2FsaG9zdCBhZGRyZXNzIGFuZCBpcyBsaWNlbnNlZCBmb3IgbG9jYWwgZGV2ZWxvcG1lbnQgdXNlIG9ubHkuDQoJCQkJPGJyIC8+PGI+QW55IG90aGVyIHVzYWdlIGlzIHByb2hpYml0ZWQgYW5kIHZpb2xhdGVzIHRoZSBIZWxpb3MgQ2FsZW5kYXIgU29mdHdhcmUgTGljZW5zZSBBZ3JlZW1lbnQ8L2I+DQoJCQk8L3A+DQoJCTwvZmllbGRzZXQ+DQoJCTxpbnB1dCBvbmNsaWNrPSJkb2N1bWVudC5sb2NhdGlvbi5ocmVmPVwnJyAuIENhbFJvb3QgLiAnL3NldHVwL2luZGV4LnBocD9zdGVwPTRcJzsiIHR5cGU9ImJ1dHRvbiIgbmFtZT0ic3VibWl0IiBpZD0ic3VibWl0IiB2YWx1ZT0iQ29udGludWUiIC8+JzsNCn0gZWxzZSB7DQoJJGhvc3QgPSAidmFsaWRhdGUucmVmcmVzaG15LmNvbSI7DQoJJGZpbGUgPSAiL2gucGhwP3Y9Mi4wJmM9IiAuICRfUE9TVFsnbGljY29kZSddIC4gIiZ1PSIgLiAkX1NFUlZFUlsnSFRUUF9IT1NUJ107DQoNCglpZighJGZwID0gZnNvY2tvcGVuKCRob3N0LCA4MCwgJGVycm5vLCAkZXJyc3RyLCAxKSl7DQoJCWVjaG8gJw0KCQk8cD4NCgkJCUNvbm5lY3Rpb24gdG8gdmFsaWRhdGlvbiBzZXJ2ZXIgZmFpbGVkLiBUaGUgZm9sbG93aW5nIGVycm9yIG1lc3NhZ2Ugd2FzIHJldHVybmVkLg0KCQkJPGJsb2NrcXVvdGU+RXJyb3IgIzonLiRlcnJuby4nIC0tICcuJGVycnN0ci4nPC9ibG9ja3F1b3RlPg0KCQkJUGxlYXNlIHdhaXQgYSBmZXcgbW9tZW50cyBhbmQgdHJ5IGFnYWluLiBJZiB5b3UgY29udGludWUgdG8gcmVjZWl2ZSB0aGlzIG1lc3NhZ2UgcGxlYXNlIHN1Ym1pdCBhIHN1cHBvcnQgdGlja2V0IGZyb20geW91ciBSZWZyZXNoIE1lbWJlcnMgU2l0ZSBhY2NvdW50IGZvciBhc3Npc3RhbmNlLg0KCQk8L3A+JzsNCgl9IGVsc2Ugew0KCQkkcmVhZCA9ICIiOw0KCQkkcmVxdWVzdCA9ICJHRVQgJGZpbGUgSFRUUC8xLjFcclxuIjsNCgkJJHJlcXVlc3QgLj0gIkhvc3Q6ICRob3N0XHJcbiI7DQoJCSRyZXF1ZXN0IC49ICJDb25uZWN0aW9uOiBDbG9zZVxyXG5cclxuIjsNCgkJZndyaXRlKCRmcCwgJHJlcXVlc3QpOw0KDQoJCXdoaWxlICghZmVvZigkZnApKQ0KCQkJJHJlYWQgLj0gZnJlYWQoJGZwLDEwMjQpOw0KDQoJCSRvdXRwdXQgPSBleHBsb2RlKCJoZWxpb3MvLyIsICRyZWFkKTsNCgkJaWYoaXNzZXQoJG91dHB1dFsxXSkpew0KCQkJJHJlZ0RhdGEgPSBleHBsb2RlKCIvLyIsIGJhc2U2NF9kZWNvZGUoJG91dHB1dFsxXSkpOw0KCQkJJF9TRVNTSU9OWyd2YWxpZCddID0gdHJ1ZTsNCgkJCSRfU0VTU0lPTlsncmVnY29kZSddID0gJF9QT1NUWydsaWNjb2RlJ107DQoJCQkkX1NFU1NJT05bJ3JlZ25hbWUnXSA9ICRyZWdEYXRhWzBdOw0KCQkJJF9TRVNTSU9OWydyZWd1cmwnXSA9ICRyZWdEYXRhWzJdOw0KCQkJJF9TRVNTSU9OWydyZWdlbWFpbCddID0gJHJlZ0RhdGFbMV07DQoNCgkJCWVjaG8gJw0KCQk8ZmllbGRzZXQ+DQoJCQlQbGVhc2UgcmV2aWV3IHlvdXIgbGljZW5zZSBpbmZvcm1hdGlvbiBiZWxvdyB0aGVuIGNsaWNrICJDb250aW51ZSIuDQoJCQk8dWw+DQoJCQkJPGxpPjxzcGFuPkxpY2Vuc2UgQ29kZTo8L3NwYW4+Jy4kX1BPU1RbJ2xpY2NvZGUnXS4nPC9saT4NCgkJCQk8bGk+PHNwYW4+TGljZW5zZWU6PC9zcGFuPicuJHJlZ0RhdGFbMF0uJzwvbGk+DQoJCQkJPGxpPjxzcGFuPkxpY2Vuc2VlIEVtYWlsOjwvc3Bhbj4nLiRyZWdEYXRhWzFdLic8L2xpPg0KCQkJCTxsaT48c3Bhbj5MaWNlbnNlZCBVUkw6PC9zcGFuPicuJHJlZ0RhdGFbMl0uJzwvbGk+DQoJCQk8L3VsPg0KCQk8L2ZpZWxkc2V0Pg0KCQk8aW5wdXQgb25jbGljaz0iZG9jdW1lbnQubG9jYXRpb24uaHJlZj1cJycgLiBDYWxSb290IC4gJy9zZXR1cC9pbmRleC5waHA/c3RlcD00XCc7IiB0eXBlPSJidXR0b24iIG5hbWU9InN1Ym1pdCIgaWQ9InN1Ym1pdCIgdmFsdWU9IkNvbnRpbnVlIiAvPic7DQoJCX0gZWxzZSB7DQoJCQllY2hvICcNCgkJPGZpZWxkc2V0Pg0KCQkJPGI+WW91ciBMaWNlbnNlIENvZGUgY291bGQgbm90IGJlIGNvbmZpcm1lZC4gVGhpcyBjYW4gaGFwcGVuIGZvciBzZXZlcmFsIHJlYXNvbnMuPC9iPg0KCQkJPHVsIGNsYXNzPSJidWxsZXRlZCI+DQoJCQkJPGxpPllvdXIgd2ViIHNlcnZlciB3YXMgdW5hYmxlIHRvIGNvbm5lY3QgdG8gUmVmcmVzaCBXZWIgRGV2ZWxvcG1lbnRcJ3MgdmFsaWRhdGlvbiBzZXJ2ZXIuPC9saT4NCgkJCQk8bGk+WW91ciBMaWNlbnNlIENvZGUgd2FzIGVudGVyZWQgaW5jb3JyZWN0bHkgKGNvbmZpcm0gaXQgaW4geW91ciBtZW1iZXIgYWNjb3VudCkuPC9saT4NCgkJCQk8bGk+WW91ciBMaWNlbnNlIENvZGUgd2FzIGNvcGllZCAmYW1wOyBwYXN0ZWQgaW5jb3JyZWN0bHkgKHdpdGggYW4gZXh0cmEgc3BhY2UvY2hhcmFjdGVyKS48L2xpPg0KCQkJCTxsaT5Zb3VyIExpY2Vuc2VkIERvbWFpbiBhbmQgdGhlIGN1cnJlbnQgaW5zdGFsbCBwb2ludCBkbyBub3QgbWF0Y2guPC9saT4NCgkJCQk8bGk+WW91IGFyZSBpbnN0YWxsaW5nIGEgdmVyc2lvbiBvZiBIZWxpb3MgQ2FsZW5kYXIgeW91ciBsaWNlbnNlIGlzIG5vdCBhdXRob3JpemVkIGZvci48L2xpPg0KCQkJCTxsaT5Zb3VyIExpY2Vuc2UgQ29kZSBpcyBpbnZhbGlkLjwvbGk+DQoJCQk8L3VsPg0KCQkJPHAgc3R5bGU9InBhZGRpbmctdG9wOjE1cHg7Ij4NCgkJCQk8Yj5UbyBwcm9jZWVkIHlvdSBzaG91bGQ6PC9iPg0KCQkJPC9wPg0KCQkJPG9sPg0KCQkJCTxsaT5Mb2dpbiB0byB5b3VyIG1lbWJlciBhY2NvdW50ICZhbXA7IGNvbmZpcm0geW91ciBMaWNlbnNlIENvZGUuPC9saT4NCgkJCQk8bGk+Q29uZmlybSB5b3VyIGN1cnJlbnQgaW5zdGFsbCBwb2ludCBtYXRjaGVzIHlvdXIgbGljZW5zZWQgZG9tYWluPC9saT4NCgkJCQk8bGk+Q2xpY2sgIlRyeSBBZ2FpbiIgYmVsb3cgYW5kIGVudGVyIHlvdXIgY29uZmlybWVkIExpY2Vuc2UgQ29kZS48L2xpPg0KCQkJPC9vbD4NCgkJCTxwIHN0eWxlPSJwYWRkaW5nLXRvcDoxNXB4OyI+DQoJCQkJPGI+Tm90ZTo8L2I+IElmIHlvdSBsaWNlbnNlZCB5b3VyIGRvbWFpbiB3aXRoIHRoZSAid3d3LiIgcHJlZml4IHlvdXIgQ2FsUm9vdCAmYW1wOyBBZG1pblJvb3QgbXVzdCBhbHNvIGluY2x1ZGUgInd3dy4iDQoJCQkJTGlrZXdpc2UsIGlmIHlvdSByZWdpc3RlcmVkIHlvdXIgbGljZW5zZSB3aXRob3V0IHRoZSAid3d3LiIgcHJlZml4IHlvdXIgQ2FsUm9vdCAmYW1wOyBBZG1pblJvb3Qgc2hvdWxkIG5vdCBpbmNsdWRlICJ3d3cuIg0KCQkJPC9wPg0KCQkJPHA+DQoJCQkJSWYgeW91IGNvbnRpbnVlIHRvIHJlY2VpdmUgdGhpcyBtZXNzYWdlIGFmdGVyIHBlcmZvcm1pbmcgdGhlIHN0ZXBzIGFib3ZlIHBsZWFzZSBzdWJtaXQgYSBzdXBwb3J0IHRpY2tldCBmcm9tIHlvdXIgUmVmcmVzaCBNZW1iZXJzIFNpdGUgYWNjb3VudCBmb3IgYXNzaXN0YW5jZS4NCgkJCTwvcD4NCgkJPC9maWVsZHNldD4NCgkJPGlucHV0IG9uY2xpY2s9ImRvY3VtZW50LmxvY2F0aW9uLmhyZWY9XCcnIC4gQ2FsUm9vdCAuICcvc2V0dXAvaW5kZXgucGhwP3N0ZXA9M1wnOyIgdHlwZT0iYnV0dG9uIiBuYW1lPSJidG4iIGlkPSJidG4iIHZhbHVlPSJUcnkgQWdhaW4iIC8+JzsNCgkJfQ0KCQlmY2xvc2UoJGZwKTsNCgl9DQp9'));
		}
	}	
?>